language: php

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '7.0'

    - os: linux
      php: hhvm

    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - _OSX=10.11
        - _PHP: php70

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash tools/prepare_osx_env.sh ; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash tools/handle_brew_pkg.sh "${_PHP}" ; fi
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --ignore-platform-reqs

script:
  - if [[ "${TRAVIS_PHP_VERSION}" = "hhv*" ]]; then php -d hhvm.php7.all=1 bin/phpunit ; fi
  - if [[ "${TRAVIS_PHP_VERSION}" = "php*" ]]; then bin/phpunit ; fi
