site_name: PHP-ML - Machine Learning library for PHP
pages:
  - Home: index.md
  - Machine Learning:
    - Classification:
      - SVC: machine-learning/classification/svc.md
      - KNearestNeighbors: machine-learning/classification/k-nearest-neighbors.md
      - NaiveBayes: machine-learning/classification/naive-bayes.md
    - Regression:
      - LeastSquares: machine-learning/regression/least-squares.md
      - SVR: machine-learning/regression/svr.md
    - Clustering:
      - KMeans: machine-learning/clustering/k-means.md
      - DBSCAN: machine-learning/clustering/dbscan.md
    - Cross Validation:
      - RandomSplit: machine-learning/cross-validation/random-split.md
    - Feature Extraction:
      - Token Count Vectorizer: machine-learning/feature-extraction/token-count-vectorizer.md
    - Datasets:
      - Array Dataset: machine-learning/datasets/array-dataset.md
      - CSV Dataset: machine-learning/datasets/csv-dataset.md
      - Ready to use datasets:
        - Iris: machine-learning/datasets/demo/iris.md
    - Metric:
      - Accuracy: machine-learning/metric/accuracy.md
  - Math:
    - Distance: math/distance.md
    - Matrix: math/matrix.md
theme: readthedocs
