site_name: PHP Machine Learning (PHP-ML)
pages:
  - Home: index.md
  - Machine Learning:
    - Classification:
      - KNearestNeighbors: machine-learning/classification/knearestneighbors.md
      - NaiveBayes: machine-learning/classification/naivebayes.md
    - Cross Validation:
      - RandomSplit: machine-learning/cross-validation/randomsplit.md
    - Datasets:
      - Array Dataset: machine-learning/datasets/array-dataset.md
      - CSV Dataset: machine-learning/datasets/csv-dataset.md
      - Demo:
        - Iris: machine-learning/datasets/demo/iris.md
    - Metric:
      - Accuracy: machine-learning/metric/accuracy.md
      - Distance:
        - Euclidean: machine-learning/metric/distance/euclidean.md
        - Chebyshev: machine-learning/metric/distance/chebyshev.md
        - Manhattan: machine-learning/metric/distance/manhattan.md
        - Minkowski: machine-learning/metric/distance/minkowski.md
theme: readthedocs